### ISSUE TITLE
Compilation error for ESP32S3 Dev Module board

### ISSUE THREAD

**Issue by Reginmand** [stooged/PS5-Dongle#1]
Greetings!
There is a device "2ASYE-T-DONGLE-S3" I encountered an error when compiling the code in the Arduino program: 1.8.19 (Linux). Couldn't send code to device. The libraries that needed to be installed were:
1. ESP32 HTTPS server https://github.com/stooged/esp32_https_server
2. ESPAsyncWebServer https://github.com/me-no-dev/ESPAsyncWebServer
3. Asynchronous TCP https://github.com/me-no-dev/AsyncTCP

I did not install drivers for Linux because this driver is needed for MS windows. Only /dev/ttyACM0 works; there are no errors on this COM port.
The device itself is checked with the command:
1. esptool -p /dev/ttyACM0 --no-stub flash_id

Simple projects can hardly be saved into the device’s memory, for example, “hello_world” works (in the esp-idf or Arduino code execution environment) through connection errors every now and then.
There are no instructions for this device because it is now popular and not everyone wants to share their project with a description.
[Arduino: 1.8.19 (Linux).txt](https://github.com/stooged/PS5-Dongle/files/15059264/Arduino.1.8.19.Linux.txt)

**Comment by stooged** [comment]
your log is telling you the error, something is broken in your "esp32_https_server-master" library

```
/home/air/Arduino/libraries/esp32_https_server-master/src/WebsocketHandler.cpp:20:5: error: 'TAG' was not declared in this scope
     TAG,
     ^~~

```


https://github.com/fhessel/esp32_https_server/blob/master/src/WebsocketHandler.cpp#L20

**Comment by Reginmand** [comment]
> ваш журнал сообщает об ошибке: что-то не так в вашей библиотеке «esp32_https_server-master»
> 
> ```
> /home/air/Arduino/libraries/esp32_https_server-master/src/WebsocketHandler.cpp:20:5: error: 'TAG' was not declared in this scope
>      TAG,
>      ^~~
> ```
> 
> [https://github.com/fhessel/esp32_https_server/blob/master/src/WebsocketHandler.cpp#L20 ](https://github.com/fhessel/esp32_https_server/blob/master/src/WebsocketHandler.cpp#L20)

Да возможно что-то не так и эти библиотеки обновляемые но в том архиве что я сохранил была (возможно) старая версия. Поэтому не получилось. Но были и другие библиотеки в большом количестве они могут создавать параллельные ошибки или конфликты версий программ (в Linux старая версия программы Arduino).

У меня получилось перепрограммировать это устройство "2ASYE-T-DONGLE-S3" через программму Arduino 2.3.2 в MS Windows 10 Pro x64 со стандартным набором библиотек и обновлений операционной системы. Но есть ошибка:
1. #warning "OpenSSL component will be removed from ESP-IDF in v5.0, please use esp_tls instead"

Не смотря на эту ошибку перепрограммирование прошло успешно 
[Arduino 2.3.2 (Windows 10 Pro X64).txt](https://github.com/stooged/PS5-Dongle/files/15072781/Arduino.2.3.2.Windows.10.Pro.X64.txt)

Хотелось-бы немного дополнить ReadMe потому что нет информации полной как правильно делать перепрошивку. И библиотеки (etahen.h, Pages.h) тоже должны быть рядом с файлом (.ino).

При подключении через Wlan и заход на сайт "http://10.1.1.1:80" работает только 4 ссылки сайта. Остальные ссылки не работают:
Внутренние страницы:
1. ☑ http://10.1.1.1/admin.html -главная целевая страница для администрирования 
![List 2 Linux](https://github.com/stooged/PS5-Dongle/assets/53215809/64c8fda9-fba4-4757-aca1-09a2a97d11d5)
2. http://10.1.1.1/info.html -предоставляет информацию о плате esp
3. ☑ http://10.1.1.1/update.html -используется для обновления прошивки на плате esp (fwupdate.bin)
4. ☑ http://10.1.1.1/config.html -используется для настройки параметров Wi-Fi и IP-адреса
5. ☑ http://10.1.1.1/restart.html -используется для перезагрузки платы esp

Пока что устройство не тестировалось с SP-Sony Playstation в будущем планирую сделать тест на SP-4-5.
